spring:
  application:
    name: cp
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: false
    open-in-view: true

server:
  port: 8081
logging:
  config: classpath:logback-dev.xml
